# Create lighttpd runtime paths in volatile tmpfs on boot
# Type  Path                           Mode  User      Group     Age  Argument
d       /var/log/lighttpd              0755  www-data  www-data  -    -
d       /var/cache/lighttpd            0755  www-data  www-data  -    -
d       /var/cache/lighttpd/uploads    0755  www-data  www-data  -    -