/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef APPUPTIMESECONDS_H
#define APPUPTIMESECONDS_H

/* function declarations */
void init_appUptimeSeconds(void);
Netsnmp_Node_Handler handle_appUptimeSeconds;

#endif /* APPUPTIMESECONDS_H */
