/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef GPIOTABLE_H
#define GPIOTABLE_H

/* function declarations */
void init_gpioTable(void);
void initialize_table_gpioTable(void);
Netsnmp_Node_Handler gpioTable_handler;
Netsnmp_First_Data_Point  gpioTable_get_first_data_point;
Netsnmp_Next_Data_Point   gpioTable_get_next_data_point;

/* column number definitions for table gpioTable */
       #define COLUMN_GPIOINDEX		1
       #define COLUMN_GPIOBCMNUMBER		2
       #define COLUMN_GPIOLOCKSTATUS		3
#endif /* GPIOTABLE_H */
